/** Compatibility barrel for the desktop visual model's region projections. */
export {
  DESKTOP_MENU_IDS,
  DESKTOP_MODE_IDS,
  DESKTOP_MODES,
  DESKTOP_PROFILE_IDS,
  DESKTOP_PROFILE_PACKAGES,
  DESKTOP_DOCK_TAB_IDS,
  DESKTOP_OVERLAY_IDS,
  DESKTOP_OVERLAY_DISMISSALS,
  DESKTOP_OVERLAY_SHORTCUTS,
  DESKTOP_DRAWER_IDS,
  DESKTOP_ASSISTANT_MODE_IDS,
  DESKTOP_ASSISTANT_RUNTIME_EVENT,
  DESKTOP_ASSISTANT_MANIPULATORS,
  DESKTOP_VISUAL_REFUSALS,
  DESKTOP_REFUSAL_MESSAGES,
  WINDOW_TIERS,
  DESKTOP_MINIMUM_WINDOW,
  DESKTOP_REFERENCE_WINDOW,
  resolveWindowTier,
  dockTabsFor,
  defaultDockTabFor,
  createDesktopVisualState,
  applyDesktopVisualAction,
  SCULPT_PASSES,
  PALETTE_GROUPS,
  VIEWPORT_INERT_NOTE,
  DESKTOP_VIEWPORT_SOURCE_IDS,
  KIDS_ASSISTANT_LOCK_CODE,
  kidsAssistantDenial,
  kidsProfileRefusal,
  desktopVisualView,
} from "./model/core.js";

export type {
  DesktopMenuId,
  DesktopModeId,
  DesktopProfileId,
  DesktopDockTabId,
  DesktopOverlayId,
  DesktopDrawerId,
  DesktopAssistantModeId,
  DesktopSculptPhase,
  DesktopAssistantState,
  DesktopAssistantRuntime,
  DesktopAssistantRoute,
  DesktopAssistantManipulatorId,
  DesktopVisualRefusal,
  DesktopWindowTierId,
  DesktopWindowSize,
  DesktopSessionState,
  DesktopVisualState,
  DesktopVisualAction,
  DesktopViewportSourceId,
  DesktopControlKind,
  DesktopControl,
  DesktopProfileChip,
  DesktopAssistantProjection,
  DesktopAssistantView,
  DesktopChangeReviewView,
  DesktopSculptView,
  DesktopOverlayView,
  DesktopVisualView,
} from "./model/core.js";
